/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package uhv1.Vistas;

import uhv1.ControlPrincipal;

/**
 *
 * @author darky
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    ControlPrincipal control;
    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal(ControlPrincipal control) {
        this.control = control;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonHabitante = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonEventos = new javax.swing.JButton();
        botonTarjeton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonHabitante.setText("HABITANTE");
        botonHabitante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonHabitanteActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Unidad Habitacional v1.0");

        botonEventos.setText("Eventos");
        botonEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEventosActionPerformed(evt);
            }
        });

        botonTarjeton.setText("Tarjeton");
        botonTarjeton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTarjetonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(botonHabitante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEventos)
                .addGap(97, 97, 97))
            .addGroup(layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(botonTarjeton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonHabitante)
                    .addComponent(botonEventos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(botonTarjeton)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonHabitanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonHabitanteActionPerformed
        dispose();
        control.controlHabitante();
    }//GEN-LAST:event_botonHabitanteActionPerformed

    private void botonEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEventosActionPerformed
        dispose();
        control.controlEventos();
    }//GEN-LAST:event_botonEventosActionPerformed

    private void botonTarjetonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTarjetonActionPerformed
        dispose();
        control.controlTarjeton();
    }//GEN-LAST:event_botonTarjetonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEventos;
    private javax.swing.JButton botonHabitante;
    private javax.swing.JButton botonTarjeton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
